import { 
  coy, 
  dark, 
  funky, 
  okaidia, 
  solarizedlight, 
  tomorrow, 
  twilight, 
  prism, 
  a11yDark, 
  atomDark, 
  base16AteliersulphurpoolLight, 
  cb, 
  coldarkCold, 
  coldarkDark, 
  coyWithoutShadows, 
  darcula, 
  dracula, 
  duotoneDark, 
  duotoneEarth, 
  duotoneForest, 
  duotoneLight, 
  duotoneSea, 
  duotoneSpace, 
  ghcolors, 
  hopscotch, 
  materialDark, 
  materialLight, 
  materialOceanic, 
  nord, 
  pojoaque, 
  shadesOfPurple, 
  synthwave84, 
  vs, 
  vscDarkPlus, 
  xonokai,
} from 'react-syntax-highlighter/dist/cjs/styles/prism';
import {
  a11yLight,
  agate,
  anOldHope,
  androidstudio,
  arduinoLight,
  arta,
  ascetic,
  atelierCaveDark,
  atelierCaveLight,
  atelierDuneDark,
  atelierDuneLight,
  atelierEstuaryDark,
  atelierEstuaryLight,
  atelierForestDark,
  atelierForestLight,
  atelierHeathDark,
  atelierHeathLight,
  atelierLakesideDark,
  atelierLakesideLight,
  atelierPlateauDark,
  atelierPlateauLight,
  atelierSavannaDark,
  atelierSavannaLight,
  atelierSeasideDark,
  atelierSeasideLight,
  atelierSulphurpoolDark,
  atelierSulphurpoolLight,
  atomOneDarkReasonable,
  atomOneDark,
  atomOneLight,
  brownPaper,
  codepenEmbed,
  colorBrewer,
  defaultStyle,
  docco,
  far,
  foundation,
  githubGist,
  github,
  gml,
  googlecode,
  gradientDark,
  gradientLight,
  grayscale,
  gruvboxDark,
  gruvboxLight,
  hybrid,
  idea,
  irBlack,
  isblEditorDark,
  isblEditorLight,
  kimbieDark,
  kimbieLight,
  lightfair,
  lioshi,
  magula,
  monoBlue,
  monokaiSublime,
  monokai,
  nightOwl,
  nnfxDark,
  nnfx,
  obsidian,
  ocean,
  paraisoDark,
  paraisoLight,
  purebasic,
  qtcreatorDark,
  qtcreatorLight,
  railscasts,
  rainbow,
  routeros,
  schoolBook,
  solarizedDark,
  solarizedLight,
  srcery,
  stackoverflowDark,
  stackoverflowLight,
  sunburst,
  tomorrowNightBlue,
  tomorrowNightBright,
  tomorrowNightEighties,
  tomorrowNight,
  vs2015,
  xcode,
  xt256,
  zenburn,
} from 'react-syntax-highlighter/dist/cjs/styles/hljs';

export const themes = {
  'coy':   coy,
  'dark': dark,
  'funky': funky,
  'okaidia': okaidia,
  'solarizedlight': solarizedlight,
  'tomorrow': tomorrow,
  'twilight': twilight,
  'prism': prism,
  'a11yDark': a11yDark,
  'atomDark': atomDark,
  'base16AteliersulphurpoolLight': base16AteliersulphurpoolLight,
  'cb': cb,
  'coldarkCold': coldarkCold,
  'coldarkDark': coldarkDark,
  'coyWithoutShadows': coyWithoutShadows,
  'darcula': darcula,
  'dracula': dracula,
  'duotoneDark': duotoneDark,
  'duotoneEarth': duotoneEarth,
  'duotoneForest': duotoneForest,
  'duotoneLight': duotoneLight,
  'duotoneSea': duotoneSea,
  'duotoneSpace': duotoneSpace,
  'ghcolors': ghcolors,
  'hopscotch': hopscotch,
  'materialDark': materialDark,
  'materialLight': materialLight,
  'materialOceanic': materialOceanic,
  'nord': nord,
  'pojoaque': pojoaque,
  'shadesOfPurple': shadesOfPurple,
  'synthwave84': synthwave84,
  'vs': vs,
  'vscDarkPlus': vscDarkPlus,
  'xonokai': xonokai,
  'a11yLight': a11yLight,
  'agate': agate,
  'anOldHope': anOldHope,
  'androidstudio': androidstudio,
  'arduinoLight': arduinoLight,
  'arta': arta,
  'ascetic': ascetic,
  'atelierCaveDark': atelierCaveDark,
  'atelierCaveLight': atelierCaveLight,
  'atelierDuneDark': atelierDuneDark,
  'atelierDuneLight': atelierDuneLight,
  'atelierEstuaryDark': atelierEstuaryDark,
  'atelierEstuaryLight': atelierEstuaryLight,
  'atelierForestDark': atelierForestDark,
  'atelierForestLight': atelierForestLight,
  'atelierHeathDark': atelierHeathDark,
  'atelierHeathLight': atelierHeathLight,
  'atelierLakesideDark': atelierLakesideDark,
  'atelierLakesideLight': atelierLakesideLight,
  'atelierPlateauDark': atelierPlateauDark,
  'atelierPlateauLight': atelierPlateauLight,
  'atelierSavannaDark': atelierSavannaDark,
  'atelierSavannaLight': atelierSavannaLight,
  'atelierSeasideDark': atelierSeasideDark,
  'atelierSeasideLight': atelierSeasideLight,
  'atelierSulphurpoolDark': atelierSulphurpoolDark,
  'atelierSulphurpoolLight': atelierSulphurpoolLight,
  'atomOneDarkReasonable': atomOneDarkReasonable,
  'atomOneDark': atomOneDark,
  'atomOneLight': atomOneLight,
  'brownPaper': brownPaper,
  'codepenEmbed': codepenEmbed,
  'colorBrewer': colorBrewer,
  'defaultStyle': defaultStyle,
  'docco': docco,
  'far': far,
  'foundation': foundation,
  'githubGist': githubGist,
  'github': github,
  'gml': gml,
  'googlecode': googlecode,
  'gradientDark': gradientDark,
  'gradientLight': gradientLight,
  'grayscale': grayscale,
  'gruvboxDark': gruvboxDark,
  'gruvboxLight': gruvboxLight,
  'hybrid': hybrid,
  'idea': idea,
  'irBlack': irBlack,
  'isblEditorDark': isblEditorDark,
  'isblEditorLight': isblEditorLight,
  'kimbieDark': kimbieDark,
  'kimbieLight': kimbieLight,
  'lightfair': lightfair,
  'lioshi': lioshi,
  'magula': magula,
  'monoBlue': monoBlue,
  'monokaiSublime': monokaiSublime,
  'monokai': monokai,
  'nightOwl': nightOwl,
  'nnfxDark': nnfxDark,
  'nnfx': nnfx,
  'obsidian': obsidian,
  'ocean': ocean,
  'paraisoDark': paraisoDark,
  'paraisoLight': paraisoLight,
  'purebasic': purebasic,
  'qtcreatorDark': qtcreatorDark,
  'qtcreatorLight': qtcreatorLight,
  'railscasts': railscasts,
  'rainbow': rainbow,
  'routeros': routeros,
  'schoolBook': schoolBook,
  'solarizedDark': solarizedDark,
  'solarizedLight': solarizedLight,
  'srcery': srcery,
  'stackoverflowDark': stackoverflowDark,
  'stackoverflowLight': stackoverflowLight,
  'sunburst': sunburst,
  'tomorrowNightBlue': tomorrowNightBlue,
  'tomorrowNightBright': tomorrowNightBright,
  'tomorrowNightEighties': tomorrowNightEighties,
  'tomorrowNight': tomorrowNight,
  'vs2015': vs2015,
  'xcode': xcode,
  'xt256': xt256,
  'zenburn': zenburn,
}